[package]
name = "ftpserver"
version = "0.1.0"
authors = ["Lunala <aurelie.saulq@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
simple-logging = "2.0.2"
ctrlc = "3.1.7"